### ISSUE TITLE
Context nesting

### ISSUE THREAD

**Issue by chrismcleod** [saturnflyer/surrounded#20]
I have an Authorizing context that accepts an AccessToken, a Permissions object, and an arbitrary sub-
context.  The Authorizing context coordinates among those objects to figure out if the sub-context is allowed to be executed.

Then in my sub-context, I have access to context.access_token,  access_token being a role in the top-level context.  The reason for nesting is so that I can execute a sub-context in the context of being authorized or by itself, so not authorized.

I'm have two questions.  

First, is context nesting the right way to go or should I just create multiple sub-contexts (auth and not auth) and pass what is needed to them from the Authorizing context?

Second, if nesting is ok, then I run into an issue when I need contexts to be nested three or more levels deep (which maybe is a bad sign).  If they are nested three levels or more, then I end up having to know to call context.context.access_token, which ends up not working if the third level sub-context is ever used as a second level sub-context.  Maybe I'm missing something in the gem or doing it wrong.  Is there a way to access other roles from parent contexts other than going through the context method in the role methods?

**Comment by saturnflyer** [comment]
Without seeing the code for it, it's difficult to say what I'd do. Using `context.context.access_token` is likely definitely a problem.

It sounds like you are _not_ treating your original context as an object itself. Can't that context be a role player inside your next context? If you need it to do something you can either define instance methods on it (as triggers if it needs access to the roles and role players) or define the methods in the role in the following context.

The internal implementation of an object should not be the concern of another. If you implement one thing as a DCI context, objects which interact with it should probably only expect the interface that they need, not that it is of a particular type of object.

Are you able to provide any generic code?

**Comment by chrismcleod** [comment]
I think the issue is that I don't fully understand how granular contexts should be.  So I'm closing this because I should discuss that elsewhere.  Thanking you for responding so quickly.

**Comment by saturnflyer** [comment]
No problem @chrismcleod. Your contexts should be as large or small as you need.
