### ISSUE TITLE
Ruby 2.2.1 Error

### ISSUE THREAD

**Issue by dmasur** [saturnflyer/surrounded#21]
Hi there,

we have a strange error happening only in 2.2.1 and maybe 2.2.0.

We have may DCI Contexts in our app and all is running smooth with ruby 2.1.5

But now all tests fail with this error:

     RuntimeError:
       can't modify frozen NilClass
     # /Users/dmasur/.rvm/gems/ruby-2.2.1/gems/surrounded-0.9.1/lib/surrounded.rb:31:in `surroundings'
     # /Users/dmasur/.rvm/gems/ruby-2.2.1/gems/surrounded-0.9.1/lib/surrounded.rb:35:in `context'
     # /Users/dmasur/.rvm/gems/ruby-2.2.1/gems/surrounded-0.9.1/lib/surrounded.rb:39:in `method_missing'

It is possible that it happened with this change: https://bugs.ruby-lang.org/issues/8923

When this error happens @__surroundings__ is nil and frozen.

When i find time i will investigate this a bit more, but at the moment i only have a private project with this problem.

**Comment by saturnflyer** [comment]
Thanks @dmasur! I'm looking into it. Do you have a simple test to provide?

**Comment by dmasur** [comment]
Hi Jim,

we found out what the problem is. we trigger a context with nil as argument. Our context checks for nix in the trigger method and react on this.

Surrounded tries to add some methods to nil before the trigger is called and ruby 2.2.1 crashes cause nil is frozen.

I hope you can reproduce this. If not leave a note and i will try to make you an app on monday.

Have a nice weekend
Dominik

**Comment by saturnflyer** [comment]
Do you intend to pass nil as an argument?

A quick answer would be to use a wrapper for that role.  Can you try that?

That may affect how your program behaves. This lead me down a path to some bugs related to using the `interface` wrapper style. I don't have a good fix for it yet but ultimately is a problem with self-schizophrenia.

**Comment by dmasur** [comment]
Yes we intend to pass nil, but now we use a NullClass (btw NullModules don't work)

Thanks for your help.
