### ISSUE TITLE
What is the best way to test the methods defined in roles?

### ISSUE THREAD

**Issue by arfl** [saturnflyer/surrounded#22]
Since all methods defined in the roles are private, what is the best way to test them?

**Comment by saturnflyer** [comment]
Test the behavior of your context object, not the individual roles.

**Comment by mhenrixon** [comment]
I just test outside in and treat the role as a black box.

**Comment by arfl** [comment]
Since I started using surrounded ( thank you @saturnflyer for your work ), I put more and more logic in the context objects. And the new methods defined in my roles can also get complicated. Would be nice to be able to test them separately somehow, because treating the context as a blackbox, so you can only call the trigger methods on them, requires usually to much of initialisation code in the tests.

**Comment by saturnflyer** [comment]
How much initialization do you require? What's a typical setup?
