### ISSUE TITLE
Is surrounded still in active develpment?

### ISSUE THREAD

**Issue by jonahx** [saturnflyer/surrounded#26]
Hey Jim, Just curious if you are still actively maintaining this project and using it in your own projects in production?  Thanks.

**Comment by saturnflyer** [comment]
Yes, and Yes. Haven't had a chance to finalize #25 with @wjdhamilton but once those changes are merged I think it'll be good for a 1.0 release.

**Comment by jonahx** [comment]
Thanks for the update and your work on this.
