### ISSUE TITLE
Cannot assign object to role using map_roles

### ISSUE THREAD

**Issue by wjdhamilton** [saturnflyer/surrounded#27]
Hi @saturnflyer 

I want to assign a couple of roles using a block in keyword_initialize like so:

  ````
 keyword_initialize :controller, :purchase_order, :params do
    it = ::Item.create!(
      name: params[:name],
      quoted_price: params[:quoted_price],
      delivery_on: params[:delivery_on]
    )
    map_roles(item: it)
  end
````

The `:item` role is definitely included in `@role_map` in the context and `#role_player? :item` returns true. However, when attempting to use `:item`a `NameError` is thrown. This is not the case for `:controller` or `:purchase_order`. Can you suggest what is going on? I have used this technique before and managed to make it work, albeit with a little fiddling...

**Comment by saturnflyer** [comment]
I'm looking into it. I'm not sure what's going on.
Are you able to provide a small test case that I can run?

**Comment by saturnflyer** [comment]
Where are you referencing `item`? What kind of implementation are you using for the role? (module, wrapper, interface, etc)

**Comment by wjdhamilton** [comment]
I'll see if I can spin up a test case once I get home, for now see the entire class:

````

**Comment by wjdhamilton** [comment]
I've set up a workspace on cloud9 that demonstrates the bug. Just run bundle exec rake test. 

If cloud9's a pain I'll create a repository on github for you instead.

**Comment by wjdhamilton** [comment]
Fixed it! Should have read the manual properly...I hadn't added `private_attr_reader :human`. Is this something that can be done automatically?

**Comment by saturnflyer** [comment]
Ah!
Well, the `keyword_initialize` method knows about the arguments but it doesn't know what happens inside the block. The responsibility for setting the `attr_reader`s is handled when defining initialization. I could see an argument for making the `role` method also set the `attr_reader` but roles might not always map directly like that.
I see this as a gotcha of using blocks with initializers. Not ideal, but I currently don't see a way around it (though I'm open to argument).
